version: '3'

services:
  city-project-server:
    image: ghcr.io/devsoleo/city-project-server:main
    container_name: city-project-server
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - CLIENT_ADDRESS=
      - PGHOST=
      - PGUSER=
      - PGPASSWORD=